namespace CourseManager
{
    enum DataColumns
    {
        Number,
        Name,
        Stage,
        Credit,
        Hour,
        CourseType,
        Teacher,
        ClassTime0,
        ClassTime1,
        ClassTime2,
        ClassTime3,
        ClassTime4,
        ClassTime5,
        ClassTime6,
        Classroom,
        NumberOfStudents,
        NumberOfDropStudents,
        TeachingAssistant,
        Language,
        Outline, 
        Note,
        Audit,
        Experiment
    }
}
